-- NEW CUSTOMERS CREATED_ONBOARDED--

select A.local_branch,
B.branch_name,
B.zone,
B.area,
 DECODE( q.GROUP_NAME, null, 
(SELECT  DISTINCT S.USER_ID || ' - ' || S.USER_NAME
 FROM CSTM_FUNCTION_USERDEF_FIELDS CSTM, SMTB_USER S
 WHERE FUNCTION_ID = 'STDCIF'
 AND (S.USER_ID = CSTM.FIELD_VAL_46 OR S.USER_NAME = CSTM.FIELD_VAL_46)
 AND REC_KEY = A.CUSTOMER_NO || '~'
 AND ROWNUM =1),
 
 (SELECT DISTINCT A.USER_ID || ' - ' || A.USER_NAME
 FROM SMTB_USER A
 WHERE 1=1
 AND A.USER_ID = q.ACCOUNT_OFFICER
 ))CSO,
A.customer_no,
A.customer_name1,
A.Customer_type,
A.customer_category,
TO_DATE(D.DATE_OF_BIRTH, 'DD-MM-RRRR') DATE_OF_BIRTH,
D.E_MAIL,
CASE WHEN D.MOBILE_NUMBER IS NULL THEN D.TELEPHONE ELSE D.MOBILE_NUMBER END MOBILE_NUMBER,
A.cif_creation_date
from sttm_customer A, sttm_branch_custom B, STTM_CUST_PERSONAL D,
(
select C.CUSTOMER_NO,c.group_code, D.GROUP_NAME, D.ACCOUNT_OFFICER , mark_for_removal
from MFTM_GROUP_MEMBER C, MFTM_GROUP_DEFINITION D
where 1=1
AND C.GROUP_CODE = D.GROUP_CODE 
AND d.RECORD_STAT = 'O'
) q
where A.local_branch = B.branch_code
and A.cif_creation_date  BETWEEN ('01-FEB-2025') AND ('28-FEB-2025')
AND A.CUSTOMER_NO = D.CUSTOMER_NO
AND D.CUSTOMER_NO = q.CUSTOMER_NO(+)